### ISSUE TITLE
Reply-to header should specify the sender's email

### ISSUE THREAD

**Issue by rlisagor** [rlisagor/ahv-council-thing#1]

**Comment by rgwood** [comment]
I looks like there is no way to add custom headers with the [`SendEmail()`](https://docs.aws.amazon.com/ses/latest/APIReference/API_SendEmail.html) we're currently using. For that we need to switch to [`SendRawEmail()`](https://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html). Bit more work than just adding the header. :(

**Comment by rgwood** [comment]
Nevermind, I missed the `ReplyToAddresses` parameter on `SendEmail()`. This should be pretty easy – I've got some time now and I will see if I can get this working.

**Comment by rgwood** [comment]
Yup that was pretty easy, just 1 line. Developed and tested while on a train to Seattle, what a time to be alive.

Pull request: https://github.com/rlisagor/ahv-council-thing/pull/9
