### ISSUE TITLE
Multiple campaigns

### ISSUE THREAD

**Issue by rlisagor** [rlisagor/ahv-council-thing#5]
It should be possible to run multiple campaigns using the same instance. Mostly, this means:

- recipient addresses should not be hardcoded, but should be set in a DB somewhere
- each message should be identified with its campaign in Slack

**Comment by rgwood** [comment]
Any objections to this approach? It's a very simple way to do things:

1. Recipient addresses are stored in the Google spreadsheet used by the letter builder
1. The letter builder passes the project ID and recipient addresses to `ahv-council-thing`

**Comment by rlisagor** [comment]
I'm a bit worried about passing arbitrary addresses through as arguments, since that could be abused. Maybe we could query the recipient list from the spreadsheet? Alternatively, we could sign the recipient list (this would remove the need for another call into the spreadsheet).

**Comment by rgwood** [comment]
> I'm a bit worried about passing arbitrary addresses through as arguments, since that could be abused. 

I had that thought as well – but I think it's a negligible risk given that we review the emails before they're sent, especially if we display the recipients in the Slack approval message.

**Comment by rlisagor** [comment]
Good point. Ok, sounds good!

**Comment by rlisagor** [comment]
Done in #10
